require("scripts.init")
require("scripts.gameplay")
gameplay = require("scripts.gameplay")
require("scripts.supercomputer")
supercomputer = require("scripts.supercomputer")
require("scripts.story")
story = require("scripts.story")
require("scripts.worms")
