util = require("util")
require("scripts.TFMG")
TFMG = require("scripts.TFMG")
require("scripts.init")

require("scripts.gameplay")
gameplay = require("scripts.gameplay")
require("scripts.supercomputer")
supercomputer = require("scripts.supercomputer")
require("scripts.story")
story = require("scripts.story")
require("scripts.ice-worm")
ice_worm = require("scripts.ice-worm")
