local TFMG = require("util.TFMG")

data:extend({
--ferric recipes
  {
    type = "recipe",
    name = "ferric-plate",
    category = "furnace",
    auto_recycle = false,
    energy_required = 1,
    enabled = false,
    ingredients = {{type = "item", name = "ferric-asteroid-chunk", amount = 1}},
    results = {{type="item", name="ferric-plate", amount=1}},
    allow_decomposition = false,
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "ferric-ore-smelting",
    category = "furnace",
    auto_recycle = false,
    energy_required = 2,
    enabled = false,
    ingredients = {{type = "item", name = "ferric-ore", amount = 2}},
    results = {{type="item", name="ferric-plate", amount=1}},
    allow_decomposition = false,
    allow_productivity = true,
    factoriopedia_alternative = "ferric-plate",
  },
  {
    type = "recipe",
    name = "pure-iron-ore-smelting",
    category = "furnace",
    auto_recycle = false,
    energy_required = 6,
    enabled = false,
    ingredients = {{type = "item", name = "pure-iron-ore", amount = 3}},
    results = {{type="item", name="ferric-plate", amount=2}},
    allow_decomposition = false,
    allow_productivity = true,
    factoriopedia_alternative = "ferric-plate",
  },
--titanium recipes
  {
    type = "recipe",
    name = "titanium-plate",
    category = "furnace",
    auto_recycle = false,
    energy_required = 8,
    enabled = false,
    ingredients = {{type = "item", name = "titanium-ore", amount = 2}},
    results = {{type="item", name="titanium-plate", amount=1}},
    allow_decomposition = false,
    allow_productivity = true,
  },
--mineral recipes
  {
    type = "recipe",
    name = "hot-mineral-plate",
    category = "furnace",
    auto_recycle = false,
    energy_required = 2,
    enabled = false,
    ingredients = {{type = "item", name = "crystalline-asteroid-chunk", amount = 1}},
    results = {{type="item", name="hot-mineral-plate", amount=1}},
    allow_decomposition = false,
    allow_productivity = true,
    result_is_always_fresh = true,
    surface_conditions = TFMG.conditions.space,
  },
  {
    type = "recipe",
    name = "mineral-glass",
    category = "furnace",
    auto_recycle = false,
    energy_required = 2,
    enabled = false,
    ingredients = {{type = "item", name = "crystalline-asteroid-chunk", amount = 1}},
    results = {{type="item", name="mineral-glass", amount=1}},
    allow_decomposition = false,
    allow_productivity = true,
    surface_conditions = TFMG.conditions.not_space,
  },
  {
    type = "recipe",
    name = "hot-mineral-plate-smelting",
    category = "furnace",
    auto_recycle = false,
    energy_required = 3,
    enabled = false,
    ingredients = {{type = "item", name = "mineral-ore", amount = 2}},
    results = {{type="item", name="hot-mineral-plate", amount=1}},
    allow_decomposition = false,
    allow_productivity = true,
    result_is_always_fresh = true,
    factoriopedia_alternative = "hot-mineral-plate",
    surface_conditions = TFMG.conditions.space,
  },
  {
    type = "recipe",
    name = "mineral-glass-smelting",
    category = "furnace",
    auto_recycle = false,
    energy_required = 3,
    enabled = false,
    ingredients = {{type = "item", name = "mineral-ore", amount = 2}},
    results = {{type="item", name="mineral-glass", amount=1}},
    allow_decomposition = false,
    allow_productivity = true,
    factoriopedia_alternative = "mineral-glass",
    surface_conditions = TFMG.conditions.not_space,
  },
  {--small radiator
    type = "recipe",
    category = "furnace",
    name = "TFMG-logo-11-tiles",
    energy_required = 60,
    enabled = true,
    hidden = true,
    ingredients = {
      { type = "item", name = "constructron", amount = 256 },
    },
    results = { 
      { type = "item", name = "TFMG-logo-11-tiles", amount = 1 }
    },
  },
})