local item_sounds = require("__base__.prototypes.item_sounds")

data:extend({
    {
    type = "item",
    name = "transport-belt-1",
    icon = "__base__/graphics/icons/transport-belt.png",
    subgroup = "belt",
    color_hint = { text = "1" },
    order = "a[transport-belt]-a",
    inventory_move_sound = item_sounds.transport_belt_inventory_move,
    pick_sound = item_sounds.transport_belt_inventory_pickup,
    drop_sound = item_sounds.transport_belt_inventory_move,
    place_result = "transport-belt-1",
    stack_size = 100
    },
    {
    type = "item",
    name = "transport-belt-2",
    icon = "__base__/graphics/icons/fast-transport-belt.png",
    subgroup = "belt",
    color_hint = { text = "1" },
    order = "a[transport-belt]-b",
    inventory_move_sound = item_sounds.transport_belt_inventory_move,
    pick_sound = item_sounds.transport_belt_inventory_pickup,
    drop_sound = item_sounds.transport_belt_inventory_move,
    place_result = "transport-belt-2",
    stack_size = 100
    },
    {
    type = "item",
    name = "underground-belt-1",
    icon = "__base__/graphics/icons/underground-belt.png",
    subgroup = "belt",
    color_hint = { text = "1" },
    order = "b[underground-belt]-a",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "underground-belt-1",
    stack_size = 50
    },
    {
    type = "item",
    name = "underground-belt-2",
    icon = "__base__/graphics/icons/fast-underground-belt.png",
    subgroup = "belt",
    color_hint = { text = "1" },
    order = "b[underground-belt]-b",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "underground-belt-2",
    stack_size = 50
    },
    {
    type = "item",
    name = "splitter-1",
    icon = "__base__/graphics/icons/splitter.png",
    subgroup = "belt",
    color_hint = { text = "1" },
    order = "c[splitter]-a",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "splitter-1",
    stack_size = 50,
    },
    {
    type = "item",
    name = "splitter-2",
    icon = "__base__/graphics/icons/fast-splitter.png",
    subgroup = "belt",
    color_hint = { text = "1" },
    order = "c[splitter]-b",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "splitter-2",
    stack_size = 50,
    },
  })