local item_sounds = require("__base__.prototypes.item_sounds")

data:extend({
  {--matter reconstructor
    type = "item",
    name = "matter-reconstructor",
    icon = "__Krastorio2Assets__/icons/entities/stabilizer-charging-station.png",
    subgroup = "production-machine",
    order = "z",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "matter-reconstructor",
    stack_size = 50,
    flags = {"always-show"},
    default_import_location = "nauvis",
  },
  {-- assembling machine
    type = "item",
    name = "assembling-machine",
    icon = "__base__/graphics/icons/assembling-machine-3.png",
    subgroup = "production-machine",
    order = "a-a",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "assembling-machine",
    stack_size = 50,
    weight = 40*kg,
    default_import_location = "nauvis",
  },
  {-- furnace
    type = "item",
    name = "furnace",
    icon = "__base__/graphics/icons/electric-furnace.png",
    subgroup = "smelting-machine",
    order = "a-b",
    inventory_move_sound = item_sounds.electric_large_inventory_move,
    pick_sound = item_sounds.electric_large_inventory_pickup,
    drop_sound = item_sounds.electric_large_inventory_move,
    place_result = "furnace",
    stack_size = 50,
    weight = 20*kg,
    default_import_location = "nauvis",
  },
  {--supercomputer
    type = "item",
    name = "supercomputer",
    icon = "__Krastorio2Assets__/icons/entities/quantum-computer.png",
    subgroup = "production-machine",
    order = "b-a",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "supercomputer",
    stack_size = 50,
    default_import_location = "nauvis",
  },
  {--supercomputer input
    type = "item",
    name = "supercomputer-input",
    icon = "__base__/graphics/icons/assembling-machine-2.png",
    hidden = true,
    hidden_in_factoriopedia =true,
    subgroup = "debug",
    order = "a-a",
    place_result = "supercomputer-input",
    stack_size = 50,
  },
  {--supercomputer output
    type = "item",
    name = "supercomputer-output",
    icon = "__base__/graphics/icons/assembling-machine-2.png",
    hidden = true,
    hidden_in_factoriopedia =true,
    subgroup = "debug",
    order = "a-b",
    place_result = "supercomputer-output",
    stack_size = 50,
  },
  {--chemistry plant
    type = "item",
    name = "chemistry-plant",
    icon = "__base__/graphics/icons/chemical-plant.png",
    subgroup = "production-machine",
    order = "a-c",
    inventory_move_sound = item_sounds.fluid_inventory_move,
    pick_sound = item_sounds.fluid_inventory_pickup,
    drop_sound = item_sounds.fluid_inventory_move,
    place_result = "chemistry-plant",
    stack_size = 10,
    default_import_location = "nauvis",
  },
  {-- refinery
    type = "item",
    name = "refinery",
    icon = "__base__/graphics/icons/oil-refinery.png",
    subgroup = "production-machine",
    order = "a-d",
    inventory_move_sound = item_sounds.fluid_inventory_move,
    pick_sound = item_sounds.fluid_inventory_pickup,
    drop_sound = item_sounds.fluid_inventory_move,
    place_result = "refinery",
    stack_size = 10,
    default_import_location = "nauvis",
  },
  {-- micro assembler
    type = "item",
    name = "micro-assembler",
    icon = "__base__/graphics/icons/assembling-machine-2.png",
    subgroup = "production-machine",
    order = "a-ab",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "micro-assembler",
    stack_size = 50,
    weight = 40*kg,
    default_import_location = "nauvis",
  },
  {--small crusher
    type = "item",
    name = "small-crusher",
    icon = "__space-age__/graphics/icons/crusher.png",
    subgroup = "production-machine",
    order = "a-e",
    inventory_move_sound = item_sounds.drill_inventory_move,
    pick_sound = item_sounds.drill_inventory_pickup,
    drop_sound = item_sounds.drill_inventory_move,
    place_result = "small-crusher",
    stack_size = 10,
    weight = 100*kg,
    default_import_location = "nauvis",
  },
})