local item_sounds = require("__base__.prototypes.item_sounds")
data:extend({
---poles
  {
    type = "item",
    name = "tiny-electric-pylon",
    icon = "__base__/graphics/icons/small-electric-pole.png",
    subgroup = "energy-pipe-distribution",
    order = "a-a",
    inventory_move_sound = item_sounds.electric_large_inventory_move,
    pick_sound = item_sounds.electric_large_inventory_pickup,
    drop_sound = item_sounds.electric_large_inventory_move,
    place_result = "tiny-electric-pylon",
    stack_size = 100
  },
  {
    type = "item",
    name = "small-electric-pylon",
    icon = "__base__/graphics/icons/medium-electric-pole.png",
    subgroup = "energy-pipe-distribution",
    order = "a-b",
    inventory_move_sound = item_sounds.electric_large_inventory_move,
    pick_sound = item_sounds.electric_large_inventory_pickup,
    drop_sound = item_sounds.electric_large_inventory_move,
    place_result = "small-electric-pylon",
    stack_size = 100
  },
  {
    type = "item",
    name = "large-electric-pylon",
    icon = "__base__/graphics/icons/big-electric-pole.png",
    subgroup = "energy-pipe-distribution",
    order = "a-d",
    inventory_move_sound = item_sounds.electric_large_inventory_move,
    pick_sound = item_sounds.electric_large_inventory_pickup,
    drop_sound = item_sounds.electric_large_inventory_move,
    place_result = "large-electric-pylon",
    stack_size = 50,
    random_tint_color = item_tints.iron_rust
  },


---generators
      {--proton decay thermoelectric generator
    type = "item",
    name = "proton-decay-thermoelectric-generator",
    icon = "__Krastorio2Assets__/icons/entities/matter-plant.png",
    subgroup = "energy",
    order = "z",
    inventory_move_sound = item_sounds.reactor_inventory_move,
    pick_sound = item_sounds.reactor_inventory_pickup,
    drop_sound = item_sounds.reactor_inventory_move,
    place_result = "proton-decay-thermoelectric-generator",
    weight = 1000 * tons,
    stack_size = 1,
    flags = {"always-show"},
  },
  {
    type = "item",
    name = "solar-cell",
    icon = "__base__/graphics/icons/solar-panel.png",
    place_as_equipment_result = "solar-cell-equipment",
    subgroup = "energy",
    order = "a[energy]-a[solar]",
    inventory_move_sound = item_sounds.electric_large_inventory_move,
    pick_sound = item_sounds.electric_large_inventory_pickup,
    drop_sound = item_sounds.electric_large_inventory_move,
    place_result = "solar-cell",
    stack_size = 50
  },
  {
    type = "item",
    name = "small-turbine",
    icon = "__base__/graphics/icons/steam-turbine.png",
    subgroup = "energy",
    order = "a[energy]-b[steam]",
    inventory_move_sound = item_sounds.steam_inventory_move,
    pick_sound = item_sounds.steam_inventory_pickup,
    drop_sound = item_sounds.steam_inventory_move,
    place_result = "small-turbine",
    stack_size = 10,
    random_tint_color = item_tints.iron_rust
  },
  {
    type = "item",
    name = "small-heat-exchanger",
    icon = "__base__/graphics/icons/heat-boiler.png",
    subgroup = "energy",
    order = "b[steam]-b[heat]",
    inventory_move_sound = item_sounds.steam_inventory_move,
    pick_sound = item_sounds.steam_inventory_pickup,
    drop_sound = item_sounds.steam_inventory_move,
    place_result = "small-heat-exchanger",
    stack_size = 50,
    weight = 40*kg,
    random_tint_color = item_tints.iron_rust
  },
  {
    type = "item",
    name = "chemical-reactor",
    icon = "__Krastorio2Assets__/icons/entities/gas-power-station.png",
    stack_size = 10,
    subgroup = "energy",
    order = "c[heat]-a[chemical]",
    place_result = "chemical-reactor",
  },
---Discharge-charge
  {
    type = "item",
    name = "charger",
    icon = "__Krastorio2Assets__/icons/entities/singularity-beacon.png",
    subgroup = "energy",
    order = "d[charger]-a[recharge]",
    place_result = "charger",
    stack_size = 50,
  },
  {
    type = "item",
    name = "discharger",
    icon = "__Krastorio2Assets__/icons/entities/tesla-coil.png",
    subgroup = "energy",
    order = "d[charger]-b[decharge]",
    place_result = "discharger",
    stack_size = 50,
  },
})