local item_sounds = require("__base__.prototypes.item_sounds")
local TFMG = require("__TFMG__.util.TFMG")
data:extend({
---energy monitor
  {
    type = "item",
    name = "energy-monitor",
    icon = "__base__/graphics/icons/accumulator.png",
    subgroup = "energy",
    order = "a-z",
    inventory_move_sound = item_sounds.electric_large_inventory_move,
    pick_sound = item_sounds.electric_large_inventory_pickup,
    drop_sound = item_sounds.electric_large_inventory_move,
    place_result = "energy-monitor",
    stack_size = 50,
    default_import_location = "nauvis",
  },
---poles


---generators
    {--proton decay thermoelectric generator
    type = "item",
    name = "proton-decay-thermoelectric-generator",
    icon = "__Krastorio2Assets__/icons/entities/matter-plant.png",
    subgroup = "energy",
    order = "z",
    inventory_move_sound = item_sounds.reactor_inventory_move,
    pick_sound = item_sounds.reactor_inventory_pickup,
    drop_sound = item_sounds.reactor_inventory_move,
    place_result = "proton-decay-thermoelectric-generator",
    weight = TFMG.rocket_capacity(1),
    stack_size = 1,
    
    flags = {"always-show"},
    default_import_location = "nauvis",
  },
  {
    type = "item",
    name = "solar-cell",
    icon = "__base__/graphics/icons/solar-panel.png",
    place_as_equipment_result = "solar-cell-equipment",
    subgroup = "energy",
    order = "a[energy]-a[solar]",
    inventory_move_sound = item_sounds.electric_large_inventory_move,
    pick_sound = item_sounds.electric_large_inventory_pickup,
    drop_sound = item_sounds.electric_large_inventory_move,
    place_result = "solar-cell",
    stack_size = 50,
    weight = TFMG.rocket_capacity(25),
    default_import_location = "nauvis",
  },
  {
    type = "item",
    name = "small-turbine",
    icon = "__base__/graphics/icons/steam-turbine.png",
    subgroup = "energy",
    order = "a[energy]-b[steam]",
    inventory_move_sound = item_sounds.steam_inventory_move,
    pick_sound = item_sounds.steam_inventory_pickup,
    drop_sound = item_sounds.steam_inventory_move,
    place_result = "small-turbine",
    stack_size = 25,
    weight = TFMG.rocket_capacity(10),
    random_tint_color = item_tints.iron_rust,
    default_import_location = "nauvis",
  },
  {
    type = "item",
    name = "small-heat-exchanger",
    icon = "__base__/graphics/icons/heat-boiler.png",
    subgroup = "energy",
    order = "b[steam]-b[heat]",
    inventory_move_sound = item_sounds.steam_inventory_move,
    pick_sound = item_sounds.steam_inventory_pickup,
    drop_sound = item_sounds.steam_inventory_move,
    place_result = "small-heat-exchanger",
    stack_size = 25,
    weight = TFMG.rocket_capacity(10),
    random_tint_color = item_tints.iron_rust,
    default_import_location = "nauvis",
  },
  {
    type = "item",
    name = "chemical-reactor",
    icon = "__Krastorio2Assets__/icons/entities/gas-power-station.png",
    stack_size = 10,
    weight = TFMG.rocket_capacity(5),
    subgroup = "energy",
    order = "c[heat]-a[chemical]",
    place_result = "chemical-reactor",
    place_as_equipment_result = "chemical-reactor-equipment",
    default_import_location = "nauvis",
  },
---Discharge-charge
  {
    type = "item",
    name = "charger",
    icon = "__Krastorio2Assets__/icons/entities/singularity-beacon.png",
    subgroup = "energy",
    order = "d[charger]-a[recharge]",
    place_result = "charger",
    stack_size = 50,
    weight = TFMG.rocket_capacity(25),
    default_import_location = "nauvis",
  },
  {
    type = "item",
    name = "discharger",
    icon = "__Krastorio2Assets__/icons/entities/tesla-coil.png",
    subgroup = "energy",
    order = "d[charger]-b[decharge]",
    place_result = "discharger",
    place_as_equipment_result = "discharger-equipment",
    stack_size = 25,
    weight = TFMG.rocket_capacity(5),
    default_import_location = "nauvis",
  },
})