data:extend({
  {
    type = "item",
    name = "ferric-asteroid-chunk",
    icon = "__TFMG__/graphics/icons/ferric-asteroid-chunk.png",
    subgroup = "raw-materials",
    order = "a[chunk]-a[ferric]",
    inventory_move_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    pick_sound = "__space-age__/sound/item/rock-inventory-pickup.ogg",
    drop_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    stack_size = 1,
    weight = 100 * kg,
    enabled = true,
  },
  {
    type = "item",
    name = "crystalline-asteroid-chunk",
    icon = "__TFMG__/graphics/icons/crystalline-asteroid-chunk.png",
    subgroup = "raw-materials",
    order = "a[chunk]-b[crystalline]",
    inventory_move_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    pick_sound = "__space-age__/sound/item/rock-inventory-pickup.ogg",
    drop_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    stack_size = 1,
    weight = 100 * kg,
    enabled = true,
  },
})