local item_sounds = require("__base__.prototypes.item_sounds")
local space_age_item_sounds = require("__space-age__.prototypes.item_sounds")
local second = 60
local minute = 3600
local TFMG = require("util.TFMG")
--Intermediates
data:extend({
---Base intermediates (Things we make other intermediates out of)
  {
    type = "item",
    name = "ferric-plate",
    icon = "__base__/graphics/icons/iron-plate.png",
    subgroup = "basic-intermediates",
    order = "a[plates]-a[ferric-plate]",
    inventory_move_sound = item_sounds.metal_small_inventory_move,
    pick_sound = item_sounds.metal_small_inventory_pickup,
    drop_sound = item_sounds.metal_small_inventory_move,
    stack_size = 100,
    random_tint_color = item_tints.iron_rust,
    default_import_location = "nauvis",
    weight = 2 * kg,
  },
  {
    type = "item",
    name = "hot-mineral-plate",
    icons = {{ icon = "__Krastorio2Assets__/icons/items/glass.png", tint = {1, 0.6, 0.6, 1}}},
    subgroup = "basic-intermediates",
    order = "b[crystal-plates]-a[hot-mineral-plate]",
    inventory_move_sound = item_sounds.metal_small_inventory_move,
    pick_sound = item_sounds.metal_small_inventory_pickup,
    drop_sound = item_sounds.metal_small_inventory_move,
    stack_size = 100,
    spoil_result = "crystalline-plate",
    spoil_ticks = 60 * second,
    default_import_location = "nauvis",
    weight = 2 * kg,
  },
  {
    type = "item",
    name = "crystalline-plate",
    icons = {{ icon = "__Krastorio2Assets__/icons/items/glass.png", tint = {0.6, 0.6, 1}}},
    subgroup = "basic-intermediates",
    order = "b[crystal-plates]-b[crystalline-plate]",
    inventory_move_sound = item_sounds.metal_small_inventory_move,
    pick_sound = item_sounds.metal_small_inventory_pickup,
    drop_sound = item_sounds.metal_small_inventory_move,
    stack_size = 100,
    default_import_location = "nauvis",
    weight = 2 * kg,
  },
  {
    type = "item",
    name = "mineral-glass",
    icons = {{ icon = "__Krastorio2Assets__/icons/items/glass.png", tint = {0.8, 1, 0.8}}},
    subgroup = "basic-intermediates",
    order = "b[crystal-plates]-c[crystalline-plate]",
    inventory_move_sound = item_sounds.metal_small_inventory_move,
    pick_sound = item_sounds.metal_small_inventory_pickup,
    drop_sound = item_sounds.metal_small_inventory_move,
    stack_size = 100,
    default_import_location = "nauvis",
    weight = 2 * kg,
  },
  {
    type = "item",
    name = "titanium-plate",
    icon = "__TFMG-assets-0__/icons/items/titanium-plate.png",
    pictures =
    {
      { size = 64, filename = "__TFMG-assets-0__/icons/items/titanium-plate.png", scale = 0.5, mipmap_count = 4 },
    },
    random_tint_color = item_tints.iron_rust,
    subgroup = "basic-intermediates",
    order = "c[titanium]-a[titanium-plate]",
    inventory_move_sound = item_sounds.metal_small_inventory_move,
    pick_sound = item_sounds.metal_small_inventory_pickup,
    drop_sound = item_sounds.metal_small_inventory_move,
    stack_size = 100,
    default_import_location = "nauvis",
    weight = 1 * kg,
  },
  {
    type = "item",
    name = "microbe-culture",
    icon = "__TFMG-assets-0__/icons/items/microbe-culture-0.png",
    pictures =
    {
      { size = 64, filename = "__TFMG-assets-0__/icons/items/microbe-culture-0.png", scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__TFMG-assets-0__/icons/items/microbe-culture-1.png", scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__TFMG-assets-0__/icons/items/microbe-culture-2.png", scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__TFMG-assets-0__/icons/items/microbe-culture-3.png", scale = 0.5, mipmap_count = 4 },
    },
    subgroup = "hydrocarbons",
    order = "a[polymers]-a[culture]",
    inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
    pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
    drop_sound = space_age_item_sounds.agriculture_inventory_move,
    stack_size = 100,
    weight = 5 * kg,
    spoil_ticks = 1 * minute,
    spoil_result = "organic-carbon",
    default_import_location = "nauvis",
  },
  {
    type = "item",
    name = "organic-carbon",
    icons = {{icon = "__base__/graphics/icons/solid-fuel.png", tint = {0.5,1,0.5}}},
    subgroup = "hydrocarbons",
    order = "a[polymers]-b[organic-carbon]",
    inventory_move_sound = item_sounds.plastic_inventory_move,
    pick_sound = item_sounds.plastic_inventory_pickup,
    drop_sound = item_sounds.plastic_inventory_move,
    stack_size = 100,
    fuel_value = "2.5MJ",
    fuel_category = "chemical",
    fuel_acceleration_multiplier = 0.5,
    fuel_top_speed_multiplier = 0.8,
    default_import_location = "nauvis",
    weight = TFMG.rocket_capacity(250),
  },
  {
    type = "item",
    name = "active-bio-polymers",
    icons = {{icon = "__base__/graphics/icons/plastic-bar.png", tint = {0.5,1,0.5}}},
    subgroup = "hydrocarbons",
    order = "a[polymers]-c[active-polymer]",
    inventory_move_sound = item_sounds.plastic_inventory_move,
    pick_sound = item_sounds.plastic_inventory_pickup,
    drop_sound = item_sounds.plastic_inventory_move,
    stack_size = 100,
    random_tint_color = item_tints.plastic,
    spoil_result = "polymer-bar",
    spoil_ticks = 60 * minute,
    default_import_location = "nauvis",
    weight = TFMG.rocket_capacity(250),
  },
  {
    type = "item",
    name = "polymer-bar",
    icon = "__base__/graphics/icons/plastic-bar.png",
    subgroup = "hydrocarbons",
    order = "a[polymers]-d[polymer]",
    inventory_move_sound = item_sounds.plastic_inventory_move,
    pick_sound = item_sounds.plastic_inventory_pickup,
    drop_sound = item_sounds.plastic_inventory_move,
    stack_size = 100,
    random_tint_color = item_tints.plastic,
    default_import_location = "nauvis",
    weight = TFMG.rocket_capacity(250),
  },
---structural intermediates (things which hold everything together)
    {--general purpose structure
    type = "item",
    name = "general-purpose-structure",
    icon = "__Krastorio2Assets__/icons/items/iron-beam.png",
    subgroup = "structural-intermediates",
    order = "a[general-purpose-structures]",
    inventory_move_sound = item_sounds.low_density_inventory_move,
    pick_sound = item_sounds.low_density_inventory_pickup,
    drop_sound = item_sounds.low_density_inventory_move,
    stack_size = 100,
    random_tint_color = item_tints.iron_rust,
    default_import_location = "nauvis",
    weight = 5 * kg,
  },
  {--high performance structure
    type = "item",
    name = "high-performance-structure",
    icon = "__TFMG-assets-0__/icons/items/high-performance-structure.png",
    subgroup = "structural-intermediates",
    order = "b[high-performacne-structures]",
    inventory_move_sound = item_sounds.low_density_inventory_move,
    pick_sound = item_sounds.low_density_inventory_pickup,
    drop_sound = item_sounds.low_density_inventory_move,
    stack_size = 50,
    random_tint_color = item_tints.iron_rust,
    default_import_location = "nauvis",
    weight = 2 * kg,
  },
---mechanical intermediates (things that make other things move)
  {--mechanical components
    type = "item",
    name = "mechanical-components",
    icon = "__Krastorio2Assets__/icons/items/automation-core.png",
    subgroup = "mechanical-intermediates",
    order = "a",
    inventory_move_sound = item_sounds.metal_large_inventory_move,
    pick_sound = item_sounds.metal_large_inventory_pickup,
    drop_sound = item_sounds.metal_large_inventory_move,
    stack_size = 100,
    random_tint_color = item_tints.iron_rust,
    default_import_location = "nauvis",
    weight = 1 * kg,
  },
  {--mechatronic components
    type = "item",
    name = "mechatronic-components",
    icon = "__Krastorio2Assets__/icons/items/ai-core.png",
    pictures = {
      layers = {
        {
          size = 64,
          filename = "__Krastorio2Assets__/icons/items/ai-core.png",
          scale = 0.5,
        },
        {
          draw_as_light = true,
          size = 64,
          filename = "__Krastorio2Assets__/icons/items/ai-core-light.png",
          scale = 0.5,
        },
      },
    },
    subgroup = "mechanical-intermediates",
    order = "b",
    inventory_move_sound = item_sounds.metal_large_inventory_move,
    pick_sound = item_sounds.metal_large_inventory_pickup,
    drop_sound = item_sounds.metal_large_inventory_move,
    stack_size = 100,
    random_tint_color = item_tints.iron_rust,
    default_import_location = "nauvis",
    weight = 1 * kg,
  },
---Electonic intermediates (things that deal with electricity)
  {--Conductive Coil
    type = "item",
    name = "conductive-coil",
    icon = "__TFMG-assets-0__/icons/items/conductive-coil.png",
    subgroup = "coil-intermediates",
    order = "a[conductive-coil]",
    inventory_move_sound = item_sounds.electric_small_inventory_move,
    pick_sound = item_sounds.electric_small_inventory_pickup,
    drop_sound = item_sounds.electric_small_inventory_move,
    stack_size = 100,
    default_import_location = "nauvis",
    weight = 0.5 * kg,
  },
  {--optical coil
    type = "item",
    name = "optical-coil",
    icon = "__TFMG-assets-0__/icons/items/optical-coil.png",
    pictures =
    {
      { size = 64, filename = "__TFMG-assets-0__/icons/items/optical-coil.png", scale = 0.5, mipmap_count = 4 },
    },
    subgroup = "coil-intermediates",
    order = "a[conductive-coil]-b",
    inventory_move_sound = item_sounds.electric_small_inventory_move,
    pick_sound = item_sounds.electric_small_inventory_pickup,
    drop_sound = item_sounds.electric_small_inventory_move,
    stack_size = 100,
    default_import_location = "nauvis",
    weight = 5 * kg,
  },
--capacitors
  {--capacitor discharged
    type = "item",
    name = "capacitor-discharged",
    localised_name = {"item-name.capacitor-discharged"},
    localised_description = {"item-description.capacitor-discharged"},
    icon = "__TFMG-assets-0__/icons/items/capacitor-discharged.png",
    subgroup = "capacitor-intermediates",
    order = "b[capacitor]-a[discharged]",
    inventory_move_sound = item_sounds.electric_small_inventory_move,
    pick_sound = item_sounds.electric_small_inventory_pickup,
    drop_sound = item_sounds.electric_small_inventory_move,
    place_as_equipment_result = "capacitor-equipment",
    stack_size = 10,
    default_import_location = "nauvis",
    pictures = {
      layers = {
        {
          filename = "__TFMG-assets-0__/icons/items/capacitor-discharged.png",
          size = 64,
          scale = 0.5,
        },
        {
          filename = "__TFMG-assets-0__/icons/items/capacitor-glow.png",
          size = 64,
          scale = 0.5,
          draw_as_light = true,
        },
      },
    },
    weight = 10 * kg,
  },
  {--capacitor charged
    type = "item",
    name = "capacitor-charged",
    icon = "__TFMG-assets-0__/icons/items/capacitor-charged.png",
    subgroup = "capacitor-intermediates",
    order = "b[capacitor]-b[charged]",
    inventory_move_sound = item_sounds.electric_small_inventory_move,
    pick_sound = item_sounds.electric_small_inventory_pickup,
    drop_sound = item_sounds.electric_small_inventory_move,
    --place_as_equipment_result = "capacitor-equipment",
    stack_size = 10,
    fuel_value = "10MJ",
    fuel_category = "electric",
    fuel_acceleration_multiplier = 1,
    fuel_top_speed_multiplier = 1,
    burnt_result = "capacitor-discharged",
    default_import_location = "nauvis",
    pictures = {
      layers = {
        {
          filename = "__TFMG-assets-0__/icons/items/capacitor-charged.png",
          size = 64,
          scale = 0.5,
        },
        {
          filename = "__TFMG-assets-0__/icons/items/capacitor-glow.png",
          size = 64,
          scale = 0.5,
          draw_as_light = true,
        },
      },
    },
    weight = 10 * kg,
  },
  --computers
  {--modular circuit
    type = "item",
    name = "modular-circuit",
    icon = "__base__/graphics/icons/electronic-circuit.png",
    subgroup = "electronic-intermediates",
    order = "c[computers]-a",
    inventory_move_sound = item_sounds.electric_small_inventory_move,
    pick_sound = item_sounds.electric_small_inventory_pickup,
    drop_sound = item_sounds.electric_small_inventory_move,
    stack_size = 200,
    default_import_location = "nauvis",
    weight = 4 * kg,
  },
  {--ai processor
    type = "item",
    name = "ai-processor",
    icon = "__space-age__/graphics/icons/quantum-processor.png",
    subgroup = "electronic-intermediates",
    order = "c[computers]-b",
    inventory_move_sound = item_sounds.electric_small_inventory_move,
    pick_sound = item_sounds.electric_small_inventory_pickup,
    drop_sound = item_sounds.electric_small_inventory_move,
    stack_size = 100,
    default_import_location = "nauvis",
    weight = 10 * kg,
  },
---advanced intermediates. (things that are complex I guess. I will likely subdivide this futher)
  {
    type = "item",
    name = "spidertron-frame",
    icon = "__space-age__/graphics/icons/rocket-turret.png",
    subgroup = "advanced-intermediates",
    order = "b[spidertron]-a[Spidertron-frame]",
    inventory_move_sound = item_sounds.electric_small_inventory_move,
    pick_sound = item_sounds.electric_small_inventory_pickup,
    drop_sound = item_sounds.electric_small_inventory_move,
    stack_size = 5,
    default_import_location = "nauvis",
  },
  {
    type = "item",
    name = "mechanical-leg",
    icon = "__base__/graphics/icons/exoskeleton-equipment.png",
    subgroup = "advanced-intermediates",
    order = "b[spiderton]-b[mechanical-leg]",
    inventory_move_sound = item_sounds.electric_small_inventory_move,
    pick_sound = item_sounds.electric_small_inventory_pickup,
    drop_sound = item_sounds.electric_small_inventory_move,
    stack_size = 5,
    place_as_equipment_result = "mechanical-leg-equipment",
    default_import_location = "nauvis",
  },
  {--excited crystalline chunk red
    type = "item",
    name = "excited-crystalline-chunk-red",
    icon = "__TFMG-assets-0__/icons/items/excited-crystalline-chunk-red.png",
    subgroup = "advanced-intermediates",
    order = "a[excited-chunk]-a",
    inventory_move_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    pick_sound = "__space-age__/sound/item/rock-inventory-pickup.ogg",
    drop_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    stack_size = 1,
    weight = 100 * kg,
    spoil_result = "excited-crystalline-chunk-blue",
    spoil_ticks = 8 * second,
    default_import_location = "nauvis",
  },
  {--excited crystalline chunk blue
    type = "item",
    name = "excited-crystalline-chunk-blue",
    icon = "__TFMG-assets-0__/icons/items/excited-crystalline-chunk-blue.png",
    subgroup = "advanced-intermediates",
    order = "a[excited-chunk]-b",
    inventory_move_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    pick_sound = "__space-age__/sound/item/rock-inventory-pickup.ogg",
    drop_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    stack_size = 1,
    weight = 100 * kg,
    spoil_result = "excited-crystalline-chunk-red",
    spoil_ticks = 8 * second,
    default_import_location = "nauvis",
  },
  {--fused crystalline chunk
    type = "item",
    name = "fused-crystalline-chunk",
    icon = "__TFMG-assets-0__/icons/items/fused-crystalline-chunk.png",
    subgroup = "advanced-intermediates",
    order = "a[excited-chunk]-c",
    inventory_move_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    pick_sound = "__space-age__/sound/item/rock-inventory-pickup.ogg",
    drop_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    stack_size = 20,
    weight = 100 * kg,
    default_import_location = "nauvis",
  },
})


data:extend({--debug items
  {
    type = "item",
    name = "kraken-uber-fuel",
    icon = "__base__/graphics/icons/nuclear-fuel.png",
    flags = {"hide-from-fuel-tooltip"},
    pictures =
    {
      layers =
      {
        {
          size = 64,
          filename = "__base__/graphics/icons/nuclear-fuel.png",
          scale = 0.5,
          mipmap_count = 4
        },
        {
          draw_as_light = true,
          size = 64,
          filename = "__base__/graphics/icons/nuclear-fuel-light.png",
          scale = 0.5
        }
      }
    },
    fuel_category = "chemical",
    fuel_value = "1000000000GJ",
    fuel_acceleration_multiplier = 10,
    fuel_top_speed_multiplier = 100,
    -- fuel_glow_color = {r = 0.1, g = 1, b = 0.1},
    subgroup = "uranium-processing",
    order = "r[uranium-processing]-e[nuclear-fuel]",
    inventory_move_sound = item_sounds.fuel_cell_inventory_move,
    pick_sound = item_sounds.fuel_cell_inventory_pickup,
    drop_sound = item_sounds.fuel_cell_inventory_move,
    stack_size = 100,
    weight = 100*kg,
    hidden = true,
    hidden_in_factoriopedia = true,
  },
})