local item_sounds = require("__base__.prototypes.item_sounds")
data:extend({
  {--ferric asteroid chunk
    type = "item",
    name = "ferric-asteroid-chunk",
    icon = "__TFMG-assets-0__/icons/ferric-asteroid-chunk.png",
    subgroup = "raw-materials",
    order = "a[chunk]-a[ferric]",
    inventory_move_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    pick_sound = "__space-age__/sound/item/rock-inventory-pickup.ogg",
    drop_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    stack_size = 20,
    weight = 100 * kg,
    flags = {"always-show"},
    default_import_location = "nauvis",
  },
  {--crystalline asteroid chunk
    type = "item",
    name = "crystalline-asteroid-chunk",
    icon = "__TFMG-assets-0__/icons/items/crystalline-chunk.png",
    subgroup = "raw-materials",
    order = "a[chunk]-b[crystalline]",
    inventory_move_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    pick_sound = "__space-age__/sound/item/rock-inventory-pickup.ogg",
    drop_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    stack_size = 20,
    weight = 100 * kg,
    flags = {"always-show"},
    default_import_location = "nauvis",
  },
  {--volatile asteroid chunk
    type = "item",
    name = "volatile-asteroid-chunk",
    icon = "__space-age__/graphics/icons/oxide-asteroid-chunk.png",
    subgroup = "raw-materials",
    order = "a[chunk]-c[volatile]",
    inventory_move_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    pick_sound = "__space-age__/sound/item/rock-inventory-pickup.ogg",
    drop_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    stack_size = 20,
    weight = 100 * kg,
    default_import_location = "nauvis",
  },
  {--ferric ore
    type = "item",
    name = "ferric-ore",
    icon = "__base__/graphics/icons/copper-ore.png",
    pictures =
    {
      { size = 64, filename = "__base__/graphics/icons/copper-ore.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__base__/graphics/icons/copper-ore-1.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__base__/graphics/icons/copper-ore-2.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__base__/graphics/icons/copper-ore-3.png",   scale = 0.5, mipmap_count = 4 },
    },
    subgroup = "raw-materials",
    order = "b[ore]-a[ferric]",
    inventory_move_sound = item_sounds.resource_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.resource_inventory_move,
    stack_size = 50,
    default_import_location = "nauvis",
    weight = 1*kg,
  },
  {--titanium ore
    type = "item",
    name = "titanium-ore",
    icon = "__base__/graphics/icons/iron-ore.png",
    pictures =
    {
      { size = 64, filename = "__base__/graphics/icons/iron-ore.png",   scale = 0.5, mipmap_count = 4},
      { size = 64, filename = "__base__/graphics/icons/iron-ore-1.png",   scale = 0.5, mipmap_count = 4},
      { size = 64, filename = "__base__/graphics/icons/iron-ore-2.png",   scale = 0.5, mipmap_count = 4},
      { size = 64, filename = "__base__/graphics/icons/iron-ore-3.png",   scale = 0.5, mipmap_count = 4},
    },
    subgroup = "raw-materials",
    order = "b[ore]-b[titanium]",
    inventory_move_sound = item_sounds.resource_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.resource_inventory_move,
    stack_size = 50,
    weight = 1*kg,
    default_import_location = "nauvis",
  },
  {--mineral ore
    type = "item",
    name = "mineral-ore",
    icon = "__TFMG-assets-0__/icons/items/mineral-ore-0.png",
    pictures =
    {
      { size = 64, filename = "__TFMG-assets-0__/icons/items/mineral-ore-0.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__TFMG-assets-0__/icons/items/mineral-ore-1.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__TFMG-assets-0__/icons/items/mineral-ore-2.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__TFMG-assets-0__/icons/items/mineral-ore-3.png",   scale = 0.5, mipmap_count = 4 },
    },
    subgroup = "raw-materials",
    order = "b[ore]-c[mineral]",
    inventory_move_sound = item_sounds.resource_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.resource_inventory_move,
    stack_size = 50,
    weight = 1*kg,
    default_import_location = "nauvis",
  },
  {--purified iron ore
    type = "item",
    name = "pure-iron-ore",
    icon = "__Krastorio2Assets__/icons/items/enriched-copper.png",
    pictures =
    {
      { size = 64, filename = "__Krastorio2Assets__/icons/items/enriched-copper.png",   scale = 0.5},
      { size = 64, filename = "__Krastorio2Assets__/icons/items/enriched-copper-1.png",   scale = 0.5},
      { size = 64, filename = "__Krastorio2Assets__/icons/items/enriched-copper-2.png",   scale = 0.5},
    },
    subgroup = "raw-materials",
    order = "c[pure]-a[ferric]",
    inventory_move_sound = item_sounds.resource_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.resource_inventory_move,
    stack_size = 50,
    weight = 1*kg,
    default_import_location = "nauvis",
  },
  {--regolith
    type = "item",
    name = "regolith",
    icon = "__space-age__/graphics/icons/big-volcanic-rock.png",
    subgroup = "raw-materials",
    order = "d[regolith]-a[regolith]",
    inventory_move_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    pick_sound = "__space-age__/sound/item/rock-inventory-pickup.ogg",
    drop_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    stack_size = 50,
    weight = 10 * kg,
    default_import_location = "extraction",
  },
  --{--crushed regolith
  --  type = "item",
  --  name = "crushed-regolith",
  --  icon = "__space-age__/graphics/icons/tungsten-ore.png",
  --  subgroup = "raw-materials",
  --  order = "d[regolith]-b[crushed-regolith]",
  --  inventory_move_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
  --  pick_sound = "__space-age__/sound/item/rock-inventory-pickup.ogg",
  --  drop_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
  --  stack_size = 50,
  --  weight = 10 * kg,
  --  default_import_location = "extraction",
  --},
})