local item_sounds = require("__base__.prototypes.item_sounds")
data:extend({
  {--ferric asteroid chunk
    type = "item",
    name = "ferric-asteroid-chunk",
    icon = "__TFMG__/graphics/icons/ferric-asteroid-chunk.png",
    subgroup = "raw-materials",
    order = "a[chunk]-a[ferric]",
    inventory_move_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    pick_sound = "__space-age__/sound/item/rock-inventory-pickup.ogg",
    drop_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    stack_size = 20,
    weight = 100 * kg,
    flags = {"always-show"},
  },
  {--crystalline asteroid chunk
    type = "item",
    name = "crystalline-asteroid-chunk",
    icon = "__TFMG__/graphics/icons/crystalline-asteroid-chunk.png",
    subgroup = "raw-materials",
    order = "a[chunk]-b[crystalline]",
    inventory_move_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    pick_sound = "__space-age__/sound/item/rock-inventory-pickup.ogg",
    drop_sound = "__space-age__/sound/item/rock-inventory-move.ogg",
    stack_size = 20,
    weight = 100 * kg,
    flags = {"always-show"},
  },
  {--ferric ore
    type = "item",
    name = "ferric-ore",
    icon = "__base__/graphics/icons/copper-ore.png",
    pictures =
    {
      { size = 64, filename = "__base__/graphics/icons/copper-ore.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__base__/graphics/icons/copper-ore-1.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__base__/graphics/icons/copper-ore-2.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__base__/graphics/icons/copper-ore-3.png",   scale = 0.5, mipmap_count = 4 },
    },
    subgroup = "raw-materials",
    order = "b[ore]-a[ferric]",
    inventory_move_sound = item_sounds.resource_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.resource_inventory_move,
    stack_size = 50,
    default_import_location = "arrival",
    weight = 1*kg,
  },
  {--titanium ore
    type = "item",
    name = "titanium-ore",
    icon = "__base__/graphics/icons/iron-ore.png",
    pictures =
    {
      { size = 64, filename = "__base__/graphics/icons/iron-ore.png",   scale = 0.5, mipmap_count = 4},
      { size = 64, filename = "__base__/graphics/icons/iron-ore-1.png",   scale = 0.5, mipmap_count = 4},
      { size = 64, filename = "__base__/graphics/icons/iron-ore-2.png",   scale = 0.5, mipmap_count = 4},
      { size = 64, filename = "__base__/graphics/icons/iron-ore-3.png",   scale = 0.5, mipmap_count = 4},
    },
    subgroup = "raw-materials",
    order = "b[ore]-b[titanium]",
    inventory_move_sound = item_sounds.resource_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.resource_inventory_move,
    stack_size = 50,
    default_import_location = "arrival",
    weight = 1*kg,
  },
  {--mineral ore
    type = "item",
    name = "mineral-ore",
    icon = "__space-age__/graphics/icons/calcite.png",
    pictures =
    {
      { size = 64, filename = "__space-age__/graphics/icons/calcite.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__space-age__/graphics/icons/calcite-1.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__space-age__/graphics/icons/calcite-2.png",   scale = 0.5, mipmap_count = 4 },
      { size = 64, filename = "__space-age__/graphics/icons/calcite-3.png",   scale = 0.5, mipmap_count = 4 },
    },
    subgroup = "raw-materials",
    order = "b[ore]-c[mineral]",
    inventory_move_sound = item_sounds.resource_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.resource_inventory_move,
    stack_size = 50,
    default_import_location = "arrival",
    weight = 1*kg,
  },
  {--purified iron ore
    type = "item",
    name = "pure-iron-ore",
    icon = "__Krastorio2Assets__/icons/items/enriched-copper.png",
    pictures =
    {
      { size = 64, filename = "__Krastorio2Assets__/icons/items/enriched-copper.png",   scale = 0.5},
      { size = 64, filename = "__Krastorio2Assets__/icons/items/enriched-copper-1.png",   scale = 0.5},
      { size = 64, filename = "__Krastorio2Assets__/icons/items/enriched-copper-2.png",   scale = 0.5},
    },
    subgroup = "raw-materials",
    order = "c[pure]-a[ferric]",
    inventory_move_sound = item_sounds.resource_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.resource_inventory_move,
    stack_size = 50,
    default_import_location = "arrival",
    weight = 1*kg,
  },
})